<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "powermailext"
 *
 * Auto generated by Extension Builder 2014-07-23
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Powermail Extended',
	'description' => 'This Extension was developed to add some functionality powermail. Features: Dependencies for Fields of other Fields: Conditional Validation and Display, Additional Validators (Date Range, IBAN), Additional HTML Tag Attributes (maxlength, disabled, readonly) for Input/Select Fields, Viewhelper for correct Text Answer in Confirmation View for Radiobuttons and Checkboxes',
	'category' => 'plugin',
	'author' => 'Ben Walch',
	'author_email' => 'ben.walch@world-direct.at',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 1,
	'version' => '1.5.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-8.99.99',
			'powermail' => '3.0.0-3.99.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);